# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/Documents/B-OOP-400-STG-4-1-raytracer-quentin.erdinger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/Documents/B-OOP-400-STG-4-1-raytracer-quentin.erdinger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documents/B-OOP-400-STG-4-1-raytracer-quentin.erdinger/CMakeFiles /home/lucas/Documents/B-OOP-400-STG-4-1-raytracer-quentin.erdinger/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documents/B-OOP-400-STG-4-1-raytracer-quentin.erdinger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/MathUtils.o: src/MathUtils.cpp.o

.PHONY : src/MathUtils.o

# target to build an object file
src/MathUtils.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/MathUtils.cpp.o
.PHONY : src/MathUtils.cpp.o

src/MathUtils.i: src/MathUtils.cpp.i

.PHONY : src/MathUtils.i

# target to preprocess a source file
src/MathUtils.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/MathUtils.cpp.i
.PHONY : src/MathUtils.cpp.i

src/MathUtils.s: src/MathUtils.cpp.s

.PHONY : src/MathUtils.s

# target to generate assembly for a file
src/MathUtils.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/MathUtils.cpp.s
.PHONY : src/MathUtils.cpp.s

src/Plane.o: src/Plane.cpp.o

.PHONY : src/Plane.o

# target to build an object file
src/Plane.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Plane.cpp.o
.PHONY : src/Plane.cpp.o

src/Plane.i: src/Plane.cpp.i

.PHONY : src/Plane.i

# target to preprocess a source file
src/Plane.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Plane.cpp.i
.PHONY : src/Plane.cpp.i

src/Plane.s: src/Plane.cpp.s

.PHONY : src/Plane.s

# target to generate assembly for a file
src/Plane.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Plane.cpp.s
.PHONY : src/Plane.cpp.s

src/Ray.o: src/Ray.cpp.o

.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i

.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s

.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/Rectangle3D.o: src/Rectangle3D.cpp.o

.PHONY : src/Rectangle3D.o

# target to build an object file
src/Rectangle3D.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Rectangle3D.cpp.o
.PHONY : src/Rectangle3D.cpp.o

src/Rectangle3D.i: src/Rectangle3D.cpp.i

.PHONY : src/Rectangle3D.i

# target to preprocess a source file
src/Rectangle3D.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Rectangle3D.cpp.i
.PHONY : src/Rectangle3D.cpp.i

src/Rectangle3D.s: src/Rectangle3D.cpp.s

.PHONY : src/Rectangle3D.s

# target to generate assembly for a file
src/Rectangle3D.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Rectangle3D.cpp.s
.PHONY : src/Rectangle3D.cpp.s

src/Sphere.o: src/Sphere.cpp.o

.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i

.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s

.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Spot.o: src/Spot.cpp.o

.PHONY : src/Spot.o

# target to build an object file
src/Spot.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Spot.cpp.o
.PHONY : src/Spot.cpp.o

src/Spot.i: src/Spot.cpp.i

.PHONY : src/Spot.i

# target to preprocess a source file
src/Spot.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Spot.cpp.i
.PHONY : src/Spot.cpp.i

src/Spot.s: src/Spot.cpp.s

.PHONY : src/Spot.s

# target to generate assembly for a file
src/Spot.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Spot.cpp.s
.PHONY : src/Spot.cpp.s

src/Vector3D.o: src/Vector3D.cpp.o

.PHONY : src/Vector3D.o

# target to build an object file
src/Vector3D.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Vector3D.cpp.o
.PHONY : src/Vector3D.cpp.o

src/Vector3D.i: src/Vector3D.cpp.i

.PHONY : src/Vector3D.i

# target to preprocess a source file
src/Vector3D.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Vector3D.cpp.i
.PHONY : src/Vector3D.cpp.i

src/Vector3D.s: src/Vector3D.cpp.s

.PHONY : src/Vector3D.s

# target to generate assembly for a file
src/Vector3D.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Vector3D.cpp.s
.PHONY : src/Vector3D.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/config/ConfigManager.o: src/utils/config/ConfigManager.cpp.o

.PHONY : src/utils/config/ConfigManager.o

# target to build an object file
src/utils/config/ConfigManager.cpp.o:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/utils/config/ConfigManager.cpp.o
.PHONY : src/utils/config/ConfigManager.cpp.o

src/utils/config/ConfigManager.i: src/utils/config/ConfigManager.cpp.i

.PHONY : src/utils/config/ConfigManager.i

# target to preprocess a source file
src/utils/config/ConfigManager.cpp.i:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/utils/config/ConfigManager.cpp.i
.PHONY : src/utils/config/ConfigManager.cpp.i

src/utils/config/ConfigManager.s: src/utils/config/ConfigManager.cpp.s

.PHONY : src/utils/config/ConfigManager.s

# target to generate assembly for a file
src/utils/config/ConfigManager.cpp.s:
	$(MAKE) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/utils/config/ConfigManager.cpp.s
.PHONY : src/utils/config/ConfigManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... raytracer"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/MathUtils.o"
	@echo "... src/MathUtils.i"
	@echo "... src/MathUtils.s"
	@echo "... src/Plane.o"
	@echo "... src/Plane.i"
	@echo "... src/Plane.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/Rectangle3D.o"
	@echo "... src/Rectangle3D.i"
	@echo "... src/Rectangle3D.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Spot.o"
	@echo "... src/Spot.i"
	@echo "... src/Spot.s"
	@echo "... src/Vector3D.o"
	@echo "... src/Vector3D.i"
	@echo "... src/Vector3D.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/config/ConfigManager.o"
	@echo "... src/utils/config/ConfigManager.i"
	@echo "... src/utils/config/ConfigManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

